import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateS211Report = (companyName: string, vendors: any[], logs: any[]) => {
  const doc = new jsPDF();

  // 1. Title Page
  doc.setFontSize(22);
  doc.text("Annual Report: Fighting Against Forced Labour", 105, 40, { align: "center" });
  doc.setFontSize(16);
  doc.text(`Entity: ${companyName}`, 105, 50, { align: "center" });
  doc.text(`Reporting Year: 2024-2025`, 105, 60, { align: "center" });

  doc.setFontSize(12);
  doc.text("Generated by S-211 Compliance Shield", 105, 70, { align: "center" });

  // 2. Mandatory Attestation (Section 11)
  doc.text("Attestation", 14, 90);
  doc.setFontSize(10);
  const attestation = "In accordance with the requirements of the Act, and in particular section 11 thereof, I attest that I have reviewed the information contained in the report for the entity or entities listed above. Based on my knowledge, and having exercised reasonable diligence, I attest that the information in the report is true, accurate and complete in all material respects.";
  
  // Split text to fit page width
  const splitText = doc.splitTextToSize(attestation, 180);
  doc.text(splitText, 14, 100);

  // 3. Steps Taken (The Data)
  doc.addPage();
  doc.setFontSize(14);
  doc.text("Section 11(3)(c): Risk Assessment & Due Diligence", 14, 20);
  
  const tableData = vendors.map(v => [
    v.company_name,
    v.country,
    v.risk_status,
    v.verification_status === 'VERIFIED' ? 'Certified' : 'Pending'
  ]);

  autoTable(doc, {
    head: [['Vendor', 'Jurisdiction', 'Risk Profile', 'Status']],
    body: tableData,
    startY: 30,
  });

  // 4. Audit Trail
  doc.addPage();
  doc.text("Audit Log (Verification of Steps Taken)", 14, 20);
  
  const logData = logs.map(l => [
    new Date(l.timestamp).toLocaleDateString(),
    l.action_type,
    l.details || '-'
  ]);

  autoTable(doc, {
    head: [['Date', 'Action', 'Detail']],
    body: logData,
    startY: 30,
  });

  // Save the file
  doc.save(`${companyName.replace(/\s+/g, '_')}_S211_Report.pdf`);
};