import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Updated Signature: accepts 'reportBody' as the 4th argument
export const generateS211Report = (
  companyName: string, 
  vendors: any[], 
  logs: any[], 
  reportBody: string // <--- The AI/User generated text
) => {
  const doc = new jsPDF();

  // --- 1. Title Page ---
  doc.setFontSize(22);
  doc.text("Annual Report: Fighting Against Forced Labour", 105, 40, { align: "center" });
  
  doc.setFontSize(16);
  doc.text(`Entity: ${companyName}`, 105, 55, { align: "center" });
  doc.text(`Reporting Year: ${new Date().getFullYear()}`, 105, 65, { align: "center" });

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text("Generated by S-211 Compliance Shield", 105, 280, { align: "center" });
  doc.setTextColor(0);

  // --- 2. Risk Assessment & Steps Taken (The Custom Content) ---
  doc.addPage();
  doc.setFontSize(14);
  doc.text("Part 1: Risk Assessment & Due Diligence", 14, 20);
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  
  // This splits the long AI text into multi-line PDF text that fits the page width
  // 180 is the max width (A4 width is ~210mm, minus margins)
  const splitBody = doc.splitTextToSize(reportBody, 180);
  doc.text(splitBody, 14, 30);

  // --- 3. Mandatory Attestation ---
  // We force a new page for the signatures to look clean and official
  doc.addPage();
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Part 2: Attestation", 14, 20);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const attestation = `In accordance with the requirements of the Act, and in particular section 11 thereof, I attest that I have reviewed the information contained in the report for the entity or entities listed above. Based on my knowledge, and having exercised reasonable diligence, I attest that the information in the report is true, accurate and complete in all material respects.`;
  
  const splitAttest = doc.splitTextToSize(attestation, 180);
  doc.text(splitAttest, 14, 30);

  // Signature Block
  doc.text("_______________________________", 14, 60);
  doc.text("Signature of Director / Officer", 14, 65);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 75);

  // --- 4. Appendix: Vendor List ---
  doc.addPage();
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Appendix A: Tier-1 Supply Chain Map", 14, 20);
  
  const tableData = vendors.map(v => [
    v.company_name || v.vendor?.company_name,
    v.country || v.vendor?.country,
    v.risk_status,
    v.verification_status === 'VERIFIED' ? 'Certified' : 'Pending'
  ]);

  autoTable(doc, {
    head: [['Vendor', 'Jurisdiction', 'Risk Profile', 'Status']],
    body: tableData,
    startY: 30,
    headStyles: { fillColor: [15, 23, 42] }, // Slate-900 style to match your brand
  });

  // Save the file with a clean name
  doc.save(`${companyName.replace(/\s+/g, '_')}_S211_Report.pdf`);
};